
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'zh';

const translations = {
  en: {
    'nav.projects': 'Projects',
    'nav.image': 'Image',
    'nav.video': 'Video',
    'nav.trash': 'Trash',
    'nav.settings': 'Settings',
    'nav.new_project': 'New Project',
    'nav.generating': 'Generating...',
    'nav.delete_confirm': 'Are you sure you want to delete this project?',
    'nav.delete_error': 'Cannot delete a project while it is generating.',
    'header.compare': 'Compare',
    'header.favorites': 'Favorites',
    'header.assets': 'Assets',
    'header.selected': 'Selected',
    'header.select_mode': 'Select',
    'header.trash': 'Recycle Bin',
    'header.trash_count': 'Items',
    'tab.parameters': 'Parameters',
    'tab.assistant': 'Creative Assistant',
    'lbl.model': 'Model',
    'lbl.prompt': 'Prompt Text',
    'lbl.negative_prompt': 'Negative Prompt',
    'lbl.seed': 'Seed',
    'lbl.aspect_ratio': 'Aspect Ratio',
    'lbl.resolution': 'Resolution',
    'lbl.count': 'Count',
    'lbl.duration': 'Duration',
    'lbl.style': 'Style',
    'lbl.advanced': 'Advanced Settings',
    'lbl.video_controls': 'Video Controls',
    'lbl.use_search': 'Use Google Search',
    'lbl.smart_assets': 'Smart Reference Assets',
    'lbl.asset_type': 'Type',
    'lbl.asset_label': 'Label (Optional)',
    'help.smart_assets': 'Upload multiple images and assign roles (Subject, Style, Composition, Edit Base) to guide generation.',
    'role.subject': 'Subject',
    'role.style': 'Style',
    'role.composition': 'Composition',
    'role.edit_base': 'Edit Base',
    'type.identity': 'Identity (Subject)',
    'type.structure': 'Structure (Layout)',
    'type.style': 'Style (Vibe)',
    'ph.label': 'e.g. Jacket, Background',
    'desc.identity': 'Decides "Who/What". Maintains facial features, product details, or character identity.',
    'desc.structure': 'Decides "Where/How". Maintains composition, pose, depth, and structure.',
    'desc.style': 'Decides "Art Style/Vibe". Extracts colors, lighting, texture, and brushstrokes.',
    'tag.person': 'Person',
    'tag.face': 'Face',
    'tag.product': 'Product',
    'tag.clothing': 'Clothing',
    'tag.background': 'Background',
    'tag.layout': 'Layout',
    'tag.pose': 'Pose',
    'tag.depth': 'Depth',
    'tag.sketch': 'Sketch',
    'tag.color': 'Color',
    'tag.lighting': 'Lighting',
    'tag.texture': 'Texture',
    'tag.artstyle': 'Art Style',
    'lbl.video_keyframes': 'Keyframes',
    'lbl.video_subject_ref': 'Subject / Character Ref',
    'lbl.video_extend': 'Extend Video',
    'lbl.continuous_mode': 'Continuous Mode',
    'lbl.text_render': 'Text to Render',
    'lbl.locked_subject': 'Locked (Subject Ref)',
    'ph.prompt.image': 'Describe the image you want to generate...',
    'ph.prompt.video': 'Describe the video you want to generate...',
    'ph.negative': 'e.g. blurry, low quality, text...',
    'ph.seed_random': 'Random (-1)',
    'ph.text_render': 'e.g. Hello World',
    'help.continuous': 'Auto-use result as next Composition Reference',
    'help.upload': 'Click or Drag to upload images',
    'help.extend_desc': 'Upload a video to extend it by 5-7 seconds. Resolution will be set to 720p.',
    'help.seed_desc': 'Locking the seed ensures consistent generation results, useful for refining prompts.',
    'help.search_desc': 'Uses Google Search to find real-time information for more accurate details.',
    'warn.cost_title': 'Extra Cost Info',
    'warn.search_cost': 'Enabling search incurs additional search query fees. Please refer to Google API pricing.',
    'help.video_subject_desc': 'Upload images (max 3) to preserve the identity of a person, character, or object in the video.',
    'note.video_ref_limit': 'Note: Subject references lock resolution to 720p.',
    'help.video_frames': 'Define the start or end of your video (optional).',
    'btn.generate': 'Generate',
    'btn.queue': 'Add to Queue',
    'btn.analyzing': 'Analyzing Chat...',
    'btn.magic_enhance': 'Magic Enhance',
    'btn.describe': 'Describe Image',
    'btn.download': 'Download',
    'btn.download_selected': 'Download Selected',
    'btn.delete': 'Delete',
    'btn.delete_selected': 'Delete Selected',
    'btn.use_ref': 'Use as Ref',
    'btn.remix': 'Remix',
    'btn.verify': 'Verify Paid Account',
    'btn.save_key': 'Save Key',
    'btn.remove_key': 'Remove Key',
    'btn.test_connection': 'Test',
    'btn.restore': 'Restore',
    'btn.delete_forever': 'Delete Forever',
    'btn.empty_trash': 'Empty Trash',
    'btn.extend': 'Extend',
    'btn.clear_edit': 'Clear Edit',
    'confirm.delete.title': 'Move to Recycle Bin?',
    'confirm.delete.desc': 'This item will be moved to the Recycle Bin. You can restore it later.',
    'confirm.delete_bulk.title': 'Delete Selected Items?',
    'confirm.empty_trash.title': 'Empty Recycle Bin?',
    'confirm.empty_trash.desc': 'This will permanently delete all items in the trash. This action cannot be undone.',
    'confirm.delete_forever.title': 'Delete Permanently?',
    'confirm.delete_forever.desc': 'This action cannot be undone.',
    'btn.cancel': 'Cancel',
    'btn.confirm': 'Confirm',
    'model.flash': 'Nano Banana',
    'model.pro': 'Nano Banana Pro',
    'model.veo_fast': 'Veo-3.1-Fast',
    'model.veo_hq': 'veo-3.1 High Quality',
    'msg.no_assets': 'No assets yet',
    'msg.no_trash': 'Recycle Bin is empty',
    'msg.generate_something': 'Generate something amazing!',
    'msg.cost_warning': 'Generations cost tokens. Check Google AI Studio for pricing.',
    'msg.connection_success': 'Connection Successful!',
    'msg.connection_failed': 'Connection Failed',
    'msg.upload_limit_count': 'Upload limit: Max 10 images.',
    'msg.upload_limit_size': 'File too large: Limit is 20MB.',
    'err.quota': 'Quota Exceeded. Please try later or use your own API Key.',
    'err.safety': 'Content blocked by safety filters. Please try a different prompt.',
    'err.network': 'Network error. Please check your connection.',
    'err.storage': 'Browser storage full. Please delete old projects.',
    'err.api_key': 'Invalid API Key. Please update in Settings.',
    'err.unknown': 'An unexpected error occurred during generation.',
    'settings.title': 'Settings',
    'settings.key_label': 'Google AI Studio API Key',
    'settings.key_desc': 'Your API key is stored locally in your browser. System does not provide a default key, so you must enter your own Google AI Studio API Key to use this application.',
    'settings.get_key': 'Get an API Key',
    'settings.custom_key_alert': 'Using custom API Key (Stored locally).',
    'settings.storage_title': 'Browser Cache',
    'settings.storage_full': 'Cache is getting full. Please empty trash or delete old projects.',
    'settings.storage_warning': '💡 Tip: Your work is stored locally in this browser. Export important projects regularly—data may be lost if you clear browser cache or run low on disk space.',
    'settings.calculating': 'Calculating usage...',
    'settings.used': 'Cache Used',
    'settings.free': 'Free',
    'chat.placeholder': 'Ask Creative Assistant...',
    'chat.welcome_video': 'Creative Assistant',
    'chat.welcome_image': 'AI Vision Studio',
    'chat.desc_video': 'Brainstorm scenes, camera angles, and prompts. Copy the final prompt to the Params tab to generate.',
    'chat.desc_image': 'Chat to create, edit, and refine images. The AI handles everything from ideation to generation.',
    'chat.thinking': 'Thinking Process',
    'chat.copied': 'Copied',
    'chat.drop_to_upload': 'Release to Upload',
    'chat.stop': 'Stop Generation',
    'chat.tools': 'Tools',
    'chat.settings_tooltip': 'Generation Settings',
    'chat.upload': 'Upload Image',
    'chat.search_on': 'Search On',
    'chat.search_off': 'Search Off',
    'editor.title': 'Editor & Inpainting',
    'editor.desc': 'Draw masks or boxes to guide the AI',
    'editor.brush': 'Paint Selection',
    'editor.box': 'Box',
    'editor.eraser': 'Eraser',
    'editor.arrow': 'Arrow',
    'editor.text': 'Text',
    'editor.text_prompt': 'Enter annotation text',
    'editor.text_placeholder': 'Type annotation...',
    'editor.size': 'Size',
    'editor.color': 'Color',
    'editor.font_size': 'Font',
    'editor.use': 'Use Image',
    'editor.reset': 'Reset All',
    'editor.undo': 'Undo',
    'editor.cancel': 'Cancel',
    'editor.regions': 'Regions',
    'editor.regions_hint': 'Add a marker or draw to create an edit region.',
    'editor.region': 'Region',
    'editor.region_placeholder': 'Describe edit for region {id}...',
    'lbl.edit_preview': 'Edit Preview',
    'help.edit_preview': 'Edit mode is active. The preview shows your base image and annotations.',
    'compare.title': 'Comparison View',
    'compare.vs': 'vs',
    'task.center': 'Task Center',
    'task.active': 'Active Tasks',
    'task.complete': 'Tasks Complete',
    'task.failed': 'Generation Failed',
    'task.processing': 'Creating...',
    'task.queued': 'Queued',
    'task.clear': 'Clear List',
    'task.waiting': 'Waiting for slot...',
    'task.running': 'Running',
    'style.NONE': 'None',
    'style.PHOTOREALISTIC': 'Photorealistic',
    'style.MINIMALIST': 'Minimalist',
    'style.LIFESTYLE': 'Lifestyle',
    'style.THREE_D_RENDER': '3D Render',
    'style.ANIME': 'Anime',
    'style.DIGITAL_ART': 'Digital Art',
    'style.COMIC_BOOK': 'Comic Book',
    'style.WATERCOLOR': 'Watercolor',
    'style.CYBERPUNK': 'Cyberpunk',
    'style.PIXEL_ART': 'Pixel Art',
    'style.SKETCH': 'Pencil Sketch',
    'style.RETRO': 'Retro Vintage',
    'style.NEON_GLOW': 'Neon Glow',
    'style.HAND_DRAWN': 'Hand Drawn',
    'style.METALLIC': 'Metallic',
    'style.MAXIMALIST': 'Maximalist',
    'style.CINEMATIC': 'Cinematic',
    'style.VINTAGE': 'Vintage Film',
    'style.NATURE': 'Nature Documentary',
    'style.DRONE': 'Drone Footage',
    'style.GLITCH': 'Glitch Art',
    'style.THREE_D': '3D Animation',
    'ratio.SQUARE': 'Square (1:1)',
    'ratio.LANDSCAPE': 'Landscape (16:9)',
    'ratio.PORTRAIT': 'Portrait (9:16)',
    'ratio.FOUR_THIRDS': 'Landscape (4:3)',
    'ratio.THREE_FOURTHS': 'Portrait (3:4)',
    'ratio.TWO_THIRDS': 'Vertical (2:3)',
    'ratio.THREE_TWOS': '35mm Film (3:2)',
    'ratio.FOUR_FIFTHS': 'Instagram (4:5)',
    'ratio.FIVE_FOURTHS': 'Large Format (5:4)',
    'ratio.ULTRAWIDE': 'Ultrawide (21:9)',
    'builder.lighting': 'Lighting',
    'builder.camera': 'Camera',
    'builder.material': 'Material',
    'builder.style': 'Style',
    'builder.vibe': 'Vibe',
    'builder.camera_move': 'Camera Move',
    'builder.motion': 'Motion',
    'builder.atmosphere': 'Atmosphere',
    'builder.lens': 'Lens/Focus',
    'bt.cinematic_lighting': 'Cinematic Lighting',
    'bt.volumetric_fog': 'Volumetric Fog',
    'bt.golden_hour': 'Golden Hour',
    'bt.neon_lights': 'Neon Lights',
    'bt.rembrandt': 'Rembrandt Lighting',
    'bt.soft_studio': 'Soft Studio Lighting',
    'bt.bioluminescence': 'Bioluminescence',
    'bt.dark_moody': 'Dark Moody',
    'bt.god_rays': 'God Rays',
    'bt.rim_lighting': 'Rim Lighting',
    'bt.wide_angle': 'Wide Angle',
    'bt.macro_lens': 'Macro Lens',
    'bt.drone_view': 'Drone View',
    'bt.gopro': 'GoPro Footage',
    'bt.bokeh': 'Bokeh Depth of Field',
    'bt.fisheye': 'Fish-eye',
    'bt.isometric': 'Isometric View',
    'bt.low_angle': 'Low Angle Shot',
    'bt.telephoto': 'Telephoto',
    'bt.motion_blur': 'Motion Blur',
    'bt.metallic': 'Metallic',
    'bt.translucent': 'Translucent',
    'bt.matte': 'Matte Finish',
    'bt.skin': 'Hyper-realistic Skin',
    'bt.glass': 'Glass Texture',
    'bt.concrete': 'Rough Concrete',
    'bt.silk': 'Silk Fabric',
    'bt.holographic': 'Holographic',
    'bt.iridescent': 'Iridescent',
    'bt.liquid_chrome': 'Liquid Chrome',
    'bt.minimalist': 'Minimalist',
    'bt.abstract': 'Abstract',
    'bt.surrealism': 'Surrealism',
    'bt.cyberpunk': 'Cyberpunk',
    'bt.steampunk': 'Steampunk',
    'bt.vaporwave': 'Vaporwave',
    'bt.gothic': 'Gothic',
    'bt.pop_art': 'Pop Art',
    'bt.ukiyo_e': 'Ukiyo-e',
    'bt.noir': 'Noir',
    'bt.chaos': 'Chaos',
    'bt.ethereal': 'Ethereal',
    'bt.gritty': 'Gritty',
    'bt.dreamy': 'Dreamy',
    'bt.epic_scale': 'Epic Scale',
    'bt.whimsical': 'Whimsical',
    'bt.melancholic': 'Melancholic',
    'bt.serene': 'Serene',
    'bt.action_packed': 'Action Packed',
    'bt.drone_shot': 'Drone Shot / Aerial',
    'bt.pan_left': 'Pan Left',
    'bt.pan_right': 'Pan Right',
    'bt.tilt_up': 'Tilt Up',
    'bt.tilt_down': 'Tilt Down',
    'bt.dolly_in': 'Dolly In (Zoom In)',
    'bt.dolly_out': 'Dolly Out (Zoom Out)',
    'bt.tracking_shot': 'Tracking Shot',
    'bt.handheld': 'Handheld Shake',
    'bt.fpv': 'FPV View',
    'bt.worms_eye': 'Low Angle / Worms Eye',
    'bt.slow_motion': 'Slow Motion',
    'bt.time_lapse': 'Time-lapse',
    'bt.hyper_lapse': 'Hyper-lapse',
    'bt.high_speed': 'High Speed Action',
    'bt.static_cam': 'Static Camera',
    'bt.freeze_frame': 'Freeze Frame',
    'bt.loop': 'Loop',
    'bt.fluid_motion': 'Fluid Motion',
    'bt.explosive': 'Explosive Action',
    'bt.vintage_film': 'Vintage Film Grain',
    'bt.foggy': 'Foggy / Hazy',
    'bt.rainy': 'Rainy / Stormy',
    'bt.sunny': 'Sunny Day',
    'bt.night_city': 'Night City Neon',
    'bt.underwater': 'Underwater',
    'bt.dusty': 'Dusty / Sandy',
    'bt.scifi_clean': 'Sci-Fi Clean',
    'bt.horror': 'Horror / Dark',
    'bt.shallow_dof': 'Shallow Depth of Field',
    'bt.deep_focus': 'Deep Focus',
    'bt.rack_focus': 'Rack Focus',
    'bt.macro_cu': 'Macro Close-up',
    'bt.wide_angle_lens': 'Wide Angle Lens',
    'bt.telephoto_lens': 'Telephoto Lens',
    'bt.fisheye_lens': 'Fish-Eye Lens',
    'bt.anamorphic': 'Anamorphic Lens',
    'tmpl.select': 'Select Template',
  },
  zh: {
    'nav.projects': '项目列表',
    'nav.image': '图像生成',
    'nav.video': '视频生成',
    'nav.trash': '回收站',
    'nav.settings': '设置',
    'nav.new_project': '新建项目',
    'nav.generating': '生成中...',
    'nav.delete_confirm': '确定要删除此项目吗？',
    'nav.delete_error': '无法删除正在生成的项目。',
    'header.compare': '对比',
    'header.favorites': '收藏',
    'header.assets': '个资源',
    'header.selected': '已选择',
    'header.select_mode': '批量选择',
    'header.trash': '回收站',
    'header.trash_count': '项',
    'tab.parameters': '快速生成',
    'tab.assistant': 'AI创意助手',
    'lbl.model': '模型选择',
    'lbl.prompt': '提示词 (Prompt)',
    'lbl.negative_prompt': '反向提示词 (Negative)',
    'lbl.seed': '随机种子 (Seed)',
    'lbl.aspect_ratio': '画面比例',
    'lbl.resolution': '分辨率',
    'lbl.count': '数量',
    'lbl.duration': '时长',
    'lbl.style': '艺术风格',
    'lbl.advanced': '高级设置',
    'lbl.video_controls': '视频控制',
    'lbl.use_search': '使用 Google 搜索增强',
    'lbl.smart_assets': '智能参考素材',
    'lbl.asset_type': '类型',
    'lbl.asset_label': '标签 (可选)',
    'help.smart_assets': '上传多张图片并指定角色（主体、风格、构图、编辑底图），用于指导生成。',
    'role.subject': '主体',
    'role.style': '风格',
    'role.composition': '构图',
    'role.edit_base': '编辑底图',
    'type.identity': '主体 (Subject)',
    'type.structure': '构图 (Structure)',
    'type.style': '风格 (Style)',
    'ph.label': '例如：外套、背景',
    'desc.identity': '决定“是谁/画什么”。保持面部特征、产品细节或角色身份的一致性。',
    'desc.structure': '决定“在哪/怎么摆”。保持画面的构图、姿势、深度和结构。',
    'desc.style': '决定“画风/色调”。提取图片的色彩、光影、纹理和笔触。',
    'tag.person': '人物',
    'tag.face': '脸部',
    'tag.product': '产品',
    'tag.clothing': '服装',
    'tag.background': '背景',
    'tag.layout': '布局',
    'tag.pose': '姿势',
    'tag.depth': '深度',
    'tag.sketch': '草图',
    'tag.color': '色彩',
    'tag.lighting': '光影',
    'tag.texture': '纹理',
    'tag.artstyle': '画风',
    'lbl.video_keyframes': '关键帧控制',
    'lbl.video_subject_ref': '主体 / 角色参考',
    'lbl.video_extend': '视频续写 (Extension)',
    'lbl.continuous_mode': '连续模式',
    'lbl.text_render': '画面文字 (Text)',
    'lbl.locked_subject': '已锁定 (角色参考)',
    'ph.prompt.image': '描述你想生成的画面...',
    'ph.prompt.video': '描述你想生成的视频内容...',
    'ph.negative': '例如：模糊、低质量、水印...',
    'ph.seed_random': '随机 (-1)',
    'ph.text_render': '例如：Happy Birthday',
    'help.continuous': '自动将生成结果作为下一张的构图参考',
    'help.upload': '点击上传',
    'help.extend_desc': '上传视频进行内容续写 (扩充 5-7秒)。注意：分辨率将锁定为 720p。',
    'help.seed_desc': '锁定种子可固定生成结果，便于在保持画面结构的同时微调细节。',
    'help.search_desc': '使用 Google 搜索获取实时信息，以生成更准确的细节。',
    'warn.cost_title': '额外费用提示',
    'warn.search_cost': '开启搜索会产生额外的搜索请求费用，具体请参考 Google API 收费说明。',
    'help.video_subject_desc': '上传图片 (最多3张) 以在视频中保持人物、角色或物体的一致性。',
    'note.video_ref_limit': '注意：使用角色参考会将分辨率锁定为 720p。',
    'help.video_frames': '定义视频的起始或结束画面（可选）。',
    'btn.generate': '开始生成',
    'btn.queue': '加入队列',
    'btn.analyzing': '分析对话中...',
    'btn.magic_enhance': '魔法优化',
    'btn.describe': '图片反推',
    'btn.download': '下载',
    'btn.download_selected': '批量下载',
    'btn.delete': '删除',
    'btn.delete_selected': '批量删除',
    'btn.use_ref': '设为参考图',
    'btn.remix': '重绘 (Remix)',
    'btn.verify': '验证付费账户',
    'btn.save_key': '保存密钥',
    'btn.remove_key': '移除密钥',
    'btn.test_connection': '测试连接',
    'btn.restore': '恢复',
    'btn.delete_forever': '彻底删除',
    'btn.empty_trash': '清空回收站',
    'btn.extend': '续写视频',
    'btn.clear_edit': '清除编辑',
    'confirm.delete.title': '移入回收站?',
    'confirm.delete.desc': '该资源将被移入回收站，你可以随时恢复它。',
    'confirm.delete_bulk.title': '删除选中项?',
    'confirm.empty_trash.title': '清空回收站?',
    'confirm.empty_trash.desc': '将永久删除回收站中的所有项目。此操作无法撤销。',
    'confirm.delete_forever.title': '彻底删除?',
    'confirm.delete_forever.desc': '此操作无法撤销。',
    'btn.cancel': '取消',
    'btn.confirm': '确认',
    'model.flash': 'Nano Banana',
    'model.pro': 'Nano Banana Pro',
    'model.veo_fast': 'Veo-3.1-Fast',
    'model.veo_hq': 'veo-3.1 High Quality',
    'msg.no_assets': '暂无资源',
    'msg.no_trash': '回收站为空',
    'msg.generate_something': '开始创造惊艳的作品吧！',
    'msg.cost_warning': '生成消耗 Token，具体定价请查看 Google AI Studio。',
    'msg.connection_success': '连接成功！网络畅通。',
    'msg.connection_failed': '连接失败',
    'msg.upload_limit_count': '上传受限：最多允许上传 10 张图片。',
    'msg.upload_limit_size': '文件过大：单张图片限制 20MB 以内。',
    'err.quota': '调用配额已耗尽。请稍后再试，或在设置中配置个人 API 密钥。',
    'err.safety': '内容由于安全过滤器被拦截。请尝试修改提示词，避开敏感描述。',
    'err.network': '网络连接错误，无法连接至服务器。请检查代理或网络环境。',
    'err.storage': '浏览器存储空间已满。请清空回收站或删除旧项目。',
    'err.api_key': 'API 密钥无效或已过期。请在设置中更新。',
    'err.unknown': '生成过程中发生意外创意故障，请重试。',
    'settings.title': '设置',
    'settings.key_label': 'Google AI Studio API Key',
    'settings.key_desc': '您的 API 密钥仅存储在本地浏览器中。系统不提供默认密钥，您必须输入自己的 Google AI Studio API Key 才能开始使用。',
    'settings.get_key': '获取 API Key',
    'settings.custom_key_alert': '正在使用自定义 API Key (已本地存储)。',
    'settings.storage_title': '浏览器缓存',
    'settings.storage_full': '缓存空间即将耗尽。请清空回收站或删除旧项目。',
    'settings.storage_warning': '💡 提示：您的作品仅保存在浏览器本地。建议及时导出重要作品，清理浏览器缓存或磁盘空间不足时数据可能丢失。',
    'settings.calculating': '正在计算缓存...',
    'settings.used': '已用缓存',
    'settings.free': '剩余',
    'chat.placeholder': '向AI创意助手提问...',
    'chat.welcome_video': 'AI创意助手',
    'chat.welcome_image': '影像创意工坊',
    'chat.desc_video': '构思场景、运镜和提示词，复制到快速生成页生成视频。',
    'chat.desc_image': '对话即可创作、编辑和优化图像，AI 全程为您服务。',
    'chat.thinking': '思考过程',
    'chat.copied': '已复制',
    'chat.drop_to_upload': '释放开始上传',
    'chat.stop': '停止生成',
    'chat.tools': '工具',
    'chat.settings_tooltip': '生成设置',
    'chat.upload': '上传图片',
    'chat.search_on': 'Google 搜索已开启',
    'chat.search_off': 'Google 搜索已关闭',
    'editor.title': '编辑与重绘',
    'editor.desc': '绘制遮罩或框选以引导 AI',
    'editor.brush': '涂抹选区',
    'editor.box': '矩形框',
    'editor.eraser': '橡皮擦',
    'editor.arrow': '箭头',
    'editor.text': '文字',
    'editor.text_prompt': '输入标注文本',
    'editor.text_placeholder': '输入标注...',
    'editor.size': '大小',
    'editor.color': '颜色',
    'editor.font_size': '字号',
    'editor.use': '使用图片',
    'editor.reset': '重置',
    'editor.undo': '撤销',
    'editor.cancel': '取消',
    'editor.regions': '编辑区域',
    'editor.regions_hint': '添加标记或绘制选区来创建编辑区域',
    'editor.region': '区域',
    'editor.region_placeholder': '描述区域 {id} 的编辑内容...',
    'lbl.edit_preview': '编辑预览',
    'help.edit_preview': '当前处于编辑模式，预览展示基础图与标注效果。',
    'compare.title': '对比视图',
    'compare.vs': '对比',
    'task.center': '任务中心',
    'task.active': '个进行中任务',
    'task.complete': '任务已完成',
    'task.failed': '生成失败',
    'task.processing': '生成中...',
    'task.queued': '排队中',
    'task.clear': '清空记录',
    'task.waiting': '等待队列...',
    'task.running': '进行中',
    'style.NONE': '无',
    'style.PHOTOREALISTIC': '写实摄影',
    'style.MINIMALIST': '极简风格',
    'style.LIFESTYLE': '生活场景',
    'style.THREE_D_RENDER': '3D 渲染',
    'style.ANIME': '动漫风格',
    'style.DIGITAL_ART': '数字艺术',
    'style.COMIC_BOOK': '漫画风格',
    'style.WATERCOLOR': '水彩画',
    'style.CYBERPUNK': '赛博朋克',
    'style.PIXEL_ART': '像素艺术',
    'style.SKETCH': '铅笔素描',
    'style.RETRO': '复古怀旧',
    'style.NEON_GLOW': '霓虹光效',
    'style.HAND_DRAWN': '手绘插画',
    'style.METALLIC': '金属质感',
    'style.MAXIMALIST': '繁复极繁',
    'style.CINEMATIC': '电影感',
    'style.VINTAGE': '复古胶片',
    'style.NATURE': '自然纪录片',
    'style.DRONE': '无人机航拍',
    'style.GLITCH': '故障艺术',
    'style.THREE_D': '3D 动画',
    'ratio.SQUARE': '正方形 (1:1)',
    'ratio.LANDSCAPE': '横屏 (16:9)',
    'ratio.PORTRAIT': '竖屏 (9:16)',
    'ratio.FOUR_THIRDS': '横屏 (4:3)',
    'ratio.THREE_FOURTHS': '竖屏 (3:4)',
    'ratio.TWO_THIRDS': '竖向 (2:3)',
    'ratio.THREE_TWOS': '电影胶片 (3:2)',
    'ratio.FOUR_FIFTHS': 'Instagram (4:5)',
    'ratio.FIVE_FOURTHS': '大画幅 (5:4)',
    'ratio.ULTRAWIDE': '超宽屏 (21:9)',
    'builder.lighting': '光影',
    'builder.camera': '运镜/视角',
    'builder.material': '材质',
    'builder.style': '风格',
    'builder.vibe': '氛围',
    'builder.camera_move': '运镜',
    'builder.motion': '动态',
    'builder.atmosphere': '环境',
    'builder.lens': '镜头/焦距',
    'bt.cinematic_lighting': '电影级布光',
    'bt.volumetric_fog': '体积雾',
    'bt.golden_hour': '黄金时刻',
    'bt.neon_lights': '霓虹灯光',
    'bt.rembrandt': '伦勃朗光',
    'bt.soft_studio': '柔和棚拍光',
    'bt.bioluminescence': '生物荧光',
    'bt.dark_moody': '暗黑情绪',
    'bt.god_rays': '丁达尔光 (神光)',
    'bt.rim_lighting': '边缘光 (轮廓光)',
    'bt.wide_angle': '广角镜头',
    'bt.macro_lens': '微距镜头',
    'bt.drone_view': '无人机俯瞰',
    'bt.gopro': 'GoPro 视角',
    'bt.bokeh': '背景虚化 (散景)',
    'bt.fisheye': '鱼眼镜头',
    'bt.isometric': '等轴测视图',
    'bt.low_angle': '低角度仰拍',
    'bt.telephoto': '长焦镜头',
    'bt.motion_blur': '动态模糊',
    'bt.metallic': '金属质感',
    'bt.translucent': '半透明',
    'bt.matte': '哑光表面',
    'bt.skin': '超写实皮肤',
    'bt.glass': '玻璃质感',
    'bt.concrete': '粗糙混凝土',
    'bt.silk': '丝绸面料',
    'bt.holographic': '全息效果',
    'bt.iridescent': '彩虹光泽',
    'bt.liquid_chrome': '液态铬',
    'bt.minimalist': '极简主义',
    'bt.abstract': '抽象艺术',
    'bt.surrealism': '超现实主义',
    'bt.cyberpunk': '赛博朋克',
    'bt.steampunk': '蒸汽朋克',
    'bt.vaporwave': '蒸汽波',
    'bt.gothic': '哥特风格',
    'bt.pop_art': '波普艺术',
    'bt.ukiyo_e': '浮世绘',
    'bt.noir': '黑色电影',
    'bt.chaos': '混乱/狂暴',
    'bt.ethereal': '空灵/飘渺',
    'bt.gritty': '粗犷/砂砾感',
    'bt.dreamy': '梦幻',
    'bt.epic_scale': '史诗宏大',
    'bt.whimsical': '异想天开',
    'bt.melancholic': '忧郁',
    'bt.serene': '宁静祥和',
    'bt.action_packed': '动作感强烈',
    'bt.drone_shot': '无人机航拍',
    'bt.pan_left': '左摇 (Pan Left)',
    'bt.pan_right': '右摇 (Pan Right)',
    'bt.tilt_up': '上摇 (Tilt Up)',
    'bt.tilt_down': '下摇 (Tilt Down)',
    'bt.dolly_in': '推镜头 (Dolly In)',
    'bt.dolly_out': '拉镜头 (Dolly Out)',
    'bt.tracking_shot': '跟拍 (Tracking)',
    'bt.handheld': '手持晃动感',
    'bt.fpv': '第一人称视角 (FPV)',
    'bt.worms_eye': '低角度/虫视',
    'bt.slow_motion': '慢动作',
    'bt.time_lapse': '延时摄影',
    'bt.hyper_lapse': '大范围延时',
    'bt.high_speed': '高速摄影',
    'bt.static_cam': '固定机位',
    'bt.freeze_frame': '定格',
    'bt.loop': '循环',
    'bt.fluid_motion': '流畅运动',
    'bt.explosive': '爆炸性动作',
    'bt.vintage_film': '复古胶片颗粒',
    'bt.foggy': '雾气/朦胧',
    'bt.rainy': '雨天/暴风雨',
    'bt.sunny': '晴朗',
    'bt.night_city': '城市夜景',
    'bt.underwater': '水下',
    'bt.dusty': '尘土飞扬',
    'bt.scifi_clean': '科幻洁净感',
    'bt.horror': '恐怖/阴暗',
    'bt.shallow_dof': '浅景深',
    'bt.deep_focus': '深焦 (全清晰)',
    'bt.rack_focus': '变焦 (Rack Focus)',
    'bt.macro_cu': '微距特写',
    'bt.wide_angle_lens': '广角镜头',
    'bt.telephoto_lens': '长焦镜头',
    'bt.fisheye_lens': '鱼眼镜头',
    'bt.anamorphic': '变形宽银幕镜头',
    'tmpl.select': '选择模板',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations['en']) => string;
}

export const LanguageContext = createContext<LanguageContextType>({
  language: 'zh',
  setLanguage: () => { },
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh');

  useEffect(() => {
    const savedLang = localStorage.getItem('app_language') as Language;
    if (savedLang && (savedLang === 'en' || savedLang === 'zh')) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: keyof typeof translations['en']) => {
    // @ts-ignore
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
